import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Bootstrap the Hermes Agent's config.yaml with the right local-only knobs
 * for our embedded scenario:
 *
 *   - model.provider:        openai_compatible
 *   - model.base_url:        http://127.0.0.1:<sigma-llama-port>/v1
 *   - browser.backend:       cdp                (use external CDP endpoint)
 *   - browser.cdp_url:       ws://127.0.0.1:<bridge>/devtools/browser/<token>
 *   - toolsets:              ["browser", "mcp"] (no voice / gateway / cron)
 *   - cloud_provider:        none               (disable Browserbase etc.)
 *
 * The launcher rewrites this file on every start so user manual edits of
 * the model/cdp/llama-port do not survive a restart — everything is derived
 * from the ports we just bound.
 */

export interface HermesConfigInputs {
  /** Active llama-server port. 0 disables the local model and points at a stub. */
  llamaPort: number;
  /** Side A CDP-mock URL (ws://127.0.0.1:<port>/devtools/browser/<token>). */
  cdpUrl: string;
  /** Hermes JSON-RPC port for the chat surface. */
  hermesRpcPort: number;
  /**
   * Active model id from prefs::kSigmaLlmLastActiveModelId. Embedded as
   * `model.id` so Hermes' OpenAI-compatible client sends the right name.
   */
  modelId?: string;
  /** Where Hermes should drop logs / state. */
  stateDir: string;
}

export function writeHermesConfig(params: {
  configPath: string;
  inputs: HermesConfigInputs;
}): void {
  const { configPath, inputs } = params;
  fs.mkdirSync(path.dirname(configPath), { recursive: true });
  // Inline the YAML manually: avoids pulling a yaml dep into the bundled
  // launcher, and the schema is small + stable enough that string templates
  // are clearer than building an object then serializing.
  const modelId = inputs.modelId ?? "sigma-local-default";
  const baseUrl =
    inputs.llamaPort > 0 ? `http://127.0.0.1:${inputs.llamaPort}/v1` : "http://127.0.0.1:0/v1";
  const lines = [
    "# Auto-generated by sigma-browser-host hermes-launcher.",
    "# Hand edits will be overwritten on every Hermes restart.",
    "",
    "model:",
    "  provider: openai_compatible",
    `  base_url: ${baseUrl}`,
    `  id: ${JSON.stringify(modelId)}`,
    `  api_key: ${JSON.stringify("sigma-local")}`,
    "",
    "browser:",
    "  backend: cdp",
    `  cdp_url: ${JSON.stringify(inputs.cdpUrl)}`,
    "  cloud_provider: none",
    "  attach_existing_targets: true",
    "",
    "toolsets:",
    "  enabled: [browser, mcp]",
    "  disabled: [voice, gateway, cron, shell, code, vision, email]",
    "",
    "rpc:",
    "  enabled: true",
    `  port: ${inputs.hermesRpcPort}`,
    "  bind: 127.0.0.1",
    "",
    "state:",
    `  dir: ${JSON.stringify(inputs.stateDir)}`,
    "",
    "safety:",
    "  redact_pii: true",
    "  approval_required_for: [browser.navigate, browser.evaluate]",
    "",
  ];
  fs.writeFileSync(configPath, lines.join("\n"), "utf8");
}
