import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Self-heal preload for Node child processes whose cwd can vanish under
 * them (Sparkle replaces the .app bundle while the gateway / hermes child
 * is running, leaving libuv's `uv_cwd` returning ENOENT on the next
 * `process.cwd()`). The launcher's C++ supervisor + spawn-time `cwd:`
 * already pin both processes to a stable per-profile directory we own —
 * this guard is the third layer in case that stable directory is somehow
 * deleted at runtime, or a future regression silently routes cwd back
 * into the bundle.
 *
 * Loaded via `node --require <stateDir>/cwd-guard.cjs` (NODE_OPTIONS).
 *
 * Behavior at boot:
 *   - Proactively chdir into OPENCLAW_STATE_DIR / HERMES_STATE_DIR (whichever
 *     is set) so the child immediately runs in the known-stable dir even if
 *     spawn-time cwd was a volatile path.
 *   - Wrap `process.cwd` so any future ENOENT/uv_cwd failure is recovered
 *     by chdir'ing back into that dir and retrying once. We log loudly and
 *     keep the wrapper installed so subsequent calls keep working.
 *
 * Pinned to CommonJS so `--require` works for any child regardless of its
 * own module format. Written verbatim into <stateDir>/cwd-guard.cjs by the
 * launcher on every startup (no bundling required, and it survives Sparkle
 * because stateDir lives in ~/Library/Application Support).
 */
const CWD_GUARD_SOURCE = `// AUTO-GENERATED by sigma-browser-host launcher on every startup.
// Do not edit by hand — changes are overwritten.
//
// Self-heal cwd preload: prevents "ENOENT: no such file or directory,
// uv_cwd" crashes when the directory that was current at spawn time gets
// deleted under the running process (Sparkle .app bundle replace, git
// branch switch in dev, etc.).

(function installCwdGuard() {
  const target =
    process.env.OPENCLAW_STATE_DIR ||
    process.env.HERMES_STATE_DIR ||
    null;
  const LOG_TAG = "[cwd-guard]";

  function safeChdir() {
    if (!target) {return false;}
    try {
      process.chdir(target);
      return true;
    } catch (err) {
      try {
        process.stderr.write(
          LOG_TAG + " chdir(" + target + ") failed: " + String(err) + "\\n",
        );
      } catch (_) {}
      return false;
    }
  }

  // Proactive: even if spawn-time cwd is fine right now, chdir into the
  // stable target so a later Sparkle bundle swap doesn't take us with it.
  safeChdir();

  // One-line boot marker so bug reports can confirm the guard is wired
  // into the running gateway (NODE_OPTIONS gets opaque fast under macOS
  // process introspection rules).
  try {
    process.stderr.write(
      LOG_TAG +
        " loaded target=" +
        (target || "<none>") +
        " cwd=" +
        process.cwd() +
        " pid=" +
        process.pid +
        "\\n",
    );
  } catch (_) {}

  // Reactive: any future process.cwd() that hits uv_cwd ENOENT triggers a
  // single chdir+retry. We keep the wrapper installed across calls so this
  // works for repeated failures too.
  const origCwd = process.cwd.bind(process);
  process.cwd = function patchedCwd() {
    try {
      return origCwd();
    } catch (err) {
      const e = /** @type {NodeJS.ErrnoException} */ (err);
      if (e && e.code === "ENOENT" && e.syscall === "uv_cwd") {
        try {
          process.stderr.write(
            LOG_TAG +
              " uv_cwd ENOENT — recovering by chdir to " +
              (target || "<none>") +
              "\\n",
          );
        } catch (_) {}
        if (safeChdir()) {
          try {
            return origCwd();
          } catch (_) {
            // fall through to throw original error
          }
        }
      }
      throw err;
    }
  };
})();
`;

/**
 * Write the cwd-guard preload into <dir>/cwd-guard.cjs on every launcher
 * boot. Idempotent: overwriting is safe even if a sibling launcher is also
 * starting because the bytes are identical (deterministic source).
 *
 * Returns the absolute path to the written file, which callers pass via
 * `NODE_OPTIONS=--require <path>` to spawned children.
 */
export function writeCwdGuardSync(dir: string): string {
  const filePath = path.join(dir, "cwd-guard.cjs");
  try {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(filePath, CWD_GUARD_SOURCE, { encoding: "utf-8" });
  } catch (err) {
    // Don't fail launcher boot just because we couldn't write the guard.
    // The C++ supervisor + spawn-time cwd already cover the common Sparkle
    // case; this is a defense-in-depth layer.
    console.warn(`[cwd-guard] writeCwdGuardSync(${dir}) failed:`, err);
  }
  return filePath;
}

/**
 * Build a NODE_OPTIONS env value that appends `--require <guardPath>` to
 * any pre-existing NODE_OPTIONS from the parent env. Returns undefined if
 * the guard path is empty, so the caller can skip setting the var at all.
 */
export function buildNodeOptionsWithGuard(
  guardPath: string,
  existing: string | undefined,
): string | undefined {
  if (!guardPath) {return existing;}
  // `--require` needs the absolute path quoted if it has spaces (it does
  // on macOS: "Application Support"). NODE_OPTIONS parses space-separated
  // tokens but treats backslash-quoted spaces correctly.
  const quoted = guardPath.includes(" ") ? `"${guardPath}"` : guardPath;
  const flag = `--require ${quoted}`;
  if (!existing || existing.trim() === "") {return flag;}
  // Avoid duplicating the flag if the parent already injected it.
  if (existing.includes(quoted)) {return existing;}
  return `${existing} ${flag}`;
}
